// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://oqfbunldiynmfyfvirwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xZmJ1bmxkaXlubWZ5ZnZpcnd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5MzExNzIsImV4cCI6MjA5MTUwNzE3Mn0.RRArLY_S8kPUhvQvVog6fMhCCauX7pVuXhmAtLV-2m4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);